# Generated by Django 3.2.3 on 2021-06-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerId', models.CharField(max_length=15)),
                ('ProductName', models.CharField(max_length=30)),
                ('Domain', models.CharField(max_length=100)),
                ('StartDate', models.DateTimeField()),
                ('Duration', models.IntegerField()),
            ],
        ),
    ]
